"""Built-in deterministic demo dataset."""

DEMO_DATA = {
    "as_of": "2026-05-13",
    "records": [
        {
            "id": "demo-nvda-computex-2026",
            "ticker": "NVDA",
            "entity": "NVIDIA Corporation",
            "event_type": "product_launch",
            "date": "2026-06-02",
            "confidence": 0.74,
            "position_size": 125000,
            "portfolio_weight": 0.0825,
            "risk_budget": 60000,
            "max_loss": 52000,
            "sector": "Information Technology",
            "theme": "AI infrastructure",
            "thesis_id": "ai-infrastructure-capex",
            "source_ref": "NVDA Computex keynote tracker",
            "status": "scheduled",
            "history": [
                {
                    "date": "2026-05-01",
                    "status": "scheduled",
                    "note": "Conference keynote timing added to calendar.",
                }
            ],
            "thesis_impact": "positive",
            "evidence_urls": [
                "https://example.com/nvidia-computex-keynote",
                "https://example.com/channel-check-gpu-supply",
            ],
            "scenario_notes": {
                "bull": "Management confirms accelerated platform demand and shorter supply constraints.",
                "base": "Product roadmap details support existing accelerator growth expectations.",
                "bear": "Launch focuses on refresh timing without incremental demand signals.",
            },
            "required_review_action": "monitor_date",
            "last_reviewed": "2026-05-09",
            "evidence_checked_at": "2026-05-09",
            "broker_views": [
                {
                    "institution": "North Coast Securities",
                    "rating": "buy",
                    "target_price": 1320.0,
                    "as_of": "2026-05-10",
                    "source_url": "https://example.com/nvda-broker-north-coast",
                    "caveat": "Target assumes accelerator backlog converts into second-half revenue.",
                },
                {
                    "institution": "Metro Capital Markets",
                    "rating": "hold",
                    "target_price": 1085.0,
                    "as_of": "2026-04-05",
                    "source_url": "https://example.com/nvda-broker-metro",
                    "caveat": "Older view predates the final Computex keynote agenda.",
                },
            ],
        },
        {
            "id": "demo-msft-earnings-2026",
            "ticker": "MSFT",
            "entity": "Microsoft Corporation",
            "event_type": "earnings",
            "date": "2026-05-06",
            "confidence": 0.82,
            "position_size": 90000,
            "portfolio_weight": 0.064,
            "risk_budget": 35000,
            "max_loss": 24000,
            "sector": "Information Technology",
            "theme": "Cloud platforms",
            "source_ref": "MSFT fiscal Q3 earnings release",
            "status": "completed",
            "history": [
                {
                    "date": "2026-04-18",
                    "status": "confirmed",
                    "note": "Earnings date confirmed from company investor relations calendar.",
                },
                {
                    "date": "2026-05-07",
                    "status": "completed",
                    "note": "Outcome recorded after company earnings release and transcript review.",
                },
            ],
            "thesis_impact": "positive",
            "evidence_urls": [
                "https://example.com/msft-q3-earnings",
                "https://ir.example.org/msft-q3-transcript",
            ],
            "scenario_notes": {
                "bull": "Cloud growth accelerates with durable margin expansion.",
                "base": "Cloud demand and operating margin track the existing thesis.",
                "bear": "Growth slows or capital spending pressure offsets revenue upside.",
            },
            "required_review_action": "none",
            "last_reviewed": "2026-05-07",
            "evidence_checked_at": "2026-05-07",
            "actual_outcome": "Cloud revenue and operating margin supported the positive thesis with no follow-up catalyst required.",
            "outcome_recorded_at": "2026-05-07",
        },
        {
            "id": "demo-pfe-fda-2026",
            "ticker": "PFE",
            "entity": "Pfizer Inc.",
            "event_type": "regulatory_decision",
            "window": {"start": "2026-05-20", "end": "2026-05-24"},
            "confidence": 0.68,
            "position_size": 48000,
            "portfolio_weight": 0.031,
            "risk_budget": 25000,
            "max_loss": 32000,
            "sector": "Health Care",
            "theme": "Pipeline reset",
            "thesis_id": "pharma-pipeline-reset",
            "source_ref": "FDA calendar and PFE pipeline note",
            "status": "watching",
            "history": [
                {
                    "date": "2026-04-28",
                    "status": "watching",
                    "note": "Regulatory decision window estimated from public review timeline.",
                }
            ],
            "thesis_impact": "mixed",
            "evidence_urls": [
                "https://example.com/fda-calendar",
                "https://example.com/pfe-pipeline-update",
            ],
            "scenario_notes": {
                "bull": "Approval expands pipeline credibility and supports forward revenue mix.",
                "base": "Decision is mostly expected but clarifies launch timing.",
                "bear": "Delay or restrictive label pressures near-term sentiment.",
            },
            "required_review_action": "verify_source",
            "last_reviewed": "2026-04-28",
            "evidence_checked_at": "2026-04-28",
            "broker_views": [
                {
                    "institution": "Harbor Life Sciences",
                    "rating": "market perform",
                    "target_price": 31.0,
                    "as_of": "2026-05-01",
                    "source_url": "https://example.com/pfe-broker-harbor",
                    "caveat": "View depends on label breadth and launch timing after the decision window.",
                },
                {
                    "institution": "Summit Research",
                    "rating": "outperform",
                    "target_price": 39.0,
                    "as_of": "2026-04-10",
                    "source_url": "https://example.com/pfe-broker-summit",
                    "caveat": "Model gives partial credit for approval but not a restrictive label.",
                },
            ],
        },
        {
            "id": "demo-fomc-june-2026",
            "ticker": "SPY",
            "entity": "S&P 500 ETF Trust",
            "event_type": "macro_release",
            "date": "2026-06-17",
            "confidence": 0.9,
            "portfolio_weight": 0.22,
            "risk_budget": 75000,
            "max_loss": 90000,
            "sector": "Macro",
            "theme": "Rates duration",
            "thesis_id": "rates-duration-risk",
            "source_ref": "FOMC public calendar",
            "status": "confirmed",
            "history": [
                {
                    "date": "2026-05-08",
                    "status": "confirmed",
                    "note": "FOMC date confirmed from public central bank calendar.",
                }
            ],
            "thesis_impact": "mixed",
            "evidence_urls": ["https://example.com/fomc-calendar"],
            "scenario_notes": {
                "bull": "Policy language indicates lower real-rate pressure for duration assets.",
                "base": "Statement broadly matches market-implied policy path.",
                "bear": "Inflation language reprices yields higher and weighs on multiples.",
            },
            "required_review_action": "monitor_date",
            "last_reviewed": "2026-05-08",
        },
    ],
}


DEMO_UPDATED_DATA = {
    "as_of": "2026-05-27",
    "records": [
        {
            "id": "demo-nvda-computex-2026",
            "ticker": "NVDA",
            "entity": "NVIDIA Corporation",
            "event_type": "product_launch",
            "date": "2026-06-02",
            "confidence": 0.81,
            "position_size": 135000,
            "portfolio_weight": 0.091,
            "risk_budget": 62000,
            "max_loss": 56000,
            "sector": "Information Technology",
            "theme": "AI infrastructure",
            "thesis_id": "ai-infrastructure-capex",
            "source_ref": "NVDA Computex keynote tracker refreshed after agenda update",
            "status": "confirmed",
            "history": [
                {
                    "date": "2026-05-01",
                    "status": "scheduled",
                    "note": "Conference keynote timing added to calendar.",
                },
                {
                    "date": "2026-05-27",
                    "status": "confirmed",
                    "note": "Company agenda confirmed keynote timing and platform focus.",
                },
            ],
            "thesis_impact": "positive",
            "evidence_urls": [
                "https://example.com/nvidia-computex-keynote",
                "https://example.com/nvidia-computex-agenda-update",
            ],
            "scenario_notes": {
                "bull": "Management confirms accelerated platform demand, tighter supply, and higher software attach.",
                "base": "Confirmed roadmap details support existing accelerator growth expectations.",
                "bear": "Launch focuses on refresh timing without incremental demand signals.",
            },
            "required_review_action": "update_scenario",
            "last_reviewed": "2026-05-27",
            "evidence_checked_at": "2026-05-27",
            "broker_views": [
                {
                    "institution": "North Coast Securities",
                    "rating": "buy",
                    "target_price": 1360.0,
                    "as_of": "2026-05-25",
                    "source_url": "https://example.com/nvda-broker-north-coast",
                    "caveat": "Target assumes accelerator backlog and networking attach convert into second-half revenue.",
                },
                {
                    "institution": "Metro Capital Markets",
                    "rating": "hold",
                    "target_price": 1085.0,
                    "as_of": "2026-04-05",
                    "source_url": "https://example.com/nvda-broker-metro",
                    "caveat": "Older view predates the final Computex keynote agenda.",
                },
            ],
        },
        {
            "id": "demo-msft-earnings-2026",
            "ticker": "MSFT",
            "entity": "Microsoft Corporation",
            "event_type": "earnings",
            "date": "2026-05-06",
            "confidence": 0.82,
            "position_size": 90000,
            "portfolio_weight": 0.064,
            "risk_budget": 35000,
            "max_loss": 24000,
            "sector": "Information Technology",
            "theme": "Cloud platforms",
            "source_ref": "MSFT fiscal Q3 earnings release",
            "status": "completed",
            "history": [
                {
                    "date": "2026-04-18",
                    "status": "confirmed",
                    "note": "Earnings date confirmed from company investor relations calendar.",
                },
                {
                    "date": "2026-05-07",
                    "status": "completed",
                    "note": "Outcome recorded after company earnings release and transcript review.",
                },
            ],
            "thesis_impact": "positive",
            "evidence_urls": [
                "https://example.com/msft-q3-earnings",
                "https://ir.example.org/msft-q3-transcript",
            ],
            "scenario_notes": {
                "bull": "Cloud growth accelerates with durable margin expansion.",
                "base": "Cloud demand and operating margin track the existing thesis.",
                "bear": "Growth slows or capital spending pressure offsets revenue upside.",
            },
            "required_review_action": "none",
            "last_reviewed": "2026-05-07",
            "evidence_checked_at": "2026-05-07",
            "actual_outcome": "Cloud revenue and operating margin supported the positive thesis with no follow-up catalyst required.",
            "outcome_recorded_at": "2026-05-07",
        },
        {
            "id": "demo-pfe-fda-2026",
            "ticker": "PFE",
            "entity": "Pfizer Inc.",
            "event_type": "regulatory_decision",
            "window": {"start": "2026-05-20", "end": "2026-05-24"},
            "confidence": 0.76,
            "position_size": 42000,
            "portfolio_weight": 0.026,
            "risk_budget": 25000,
            "max_loss": 18000,
            "sector": "Health Care",
            "theme": "Pipeline reset",
            "thesis_id": "pharma-pipeline-reset",
            "source_ref": "FDA calendar, label note, and PFE pipeline update",
            "status": "completed",
            "history": [
                {
                    "date": "2026-04-28",
                    "status": "watching",
                    "note": "Regulatory decision window estimated from public review timeline.",
                },
                {
                    "date": "2026-05-24",
                    "status": "completed",
                    "note": "Decision posted before the review window closed.",
                },
            ],
            "thesis_impact": "positive",
            "evidence_urls": [
                "https://example.com/fda-calendar",
                "https://example.com/pfe-label-update",
            ],
            "scenario_notes": {
                "bull": "Approval expands pipeline credibility and supports forward revenue mix.",
                "base": "Approval arrived inside the expected window and clarifies launch timing.",
                "bear": "Label restrictions would still limit near-term uptake.",
            },
            "required_review_action": "archive",
            "last_reviewed": "2026-05-24",
            "evidence_checked_at": "2026-05-24",
            "broker_views": [
                {
                    "institution": "Harbor Life Sciences",
                    "rating": "market perform",
                    "target_price": 33.0,
                    "as_of": "2026-05-24",
                    "source_url": "https://example.com/pfe-broker-harbor",
                    "caveat": "View now gives more credit for label breadth after the decision window.",
                },
                {
                    "institution": "Summit Research",
                    "rating": "outperform",
                    "target_price": 39.0,
                    "as_of": "2026-04-10",
                    "source_url": "https://example.com/pfe-broker-summit",
                    "caveat": "Model gives partial credit for approval but not a restrictive label.",
                },
            ],
            "actual_outcome": "Approval arrived inside the expected decision window with label language better than the base case.",
            "outcome_recorded_at": "2026-05-24",
        },
        {
            "id": "demo-amzn-kuiper-2026",
            "ticker": "AMZN",
            "entity": "Amazon.com Inc.",
            "event_type": "product_launch",
            "date": "2026-06-12",
            "confidence": 0.63,
            "position_size": 70000,
            "portfolio_weight": 0.044,
            "risk_budget": 30000,
            "max_loss": 36000,
            "sector": "Communication Services",
            "theme": "Satellite broadband",
            "thesis_id": "ai-infrastructure-capex",
            "source_ref": "Kuiper launch readiness note",
            "status": "watching",
            "history": [
                {
                    "date": "2026-05-26",
                    "status": "watching",
                    "note": "Added after supplier and launch readiness notes pointed to a June milestone.",
                }
            ],
            "thesis_impact": "mixed",
            "evidence_urls": [
                "https://example.com/amzn-kuiper-readiness",
                "https://example.com/space-launch-manifest",
            ],
            "scenario_notes": {
                "bull": "Launch milestone supports services optionality without near-term capex surprise.",
                "base": "Launch validates roadmap but keeps investment spending elevated.",
                "bear": "Delay or cost escalation adds pressure to margin expectations.",
            },
            "required_review_action": "verify_source",
            "last_reviewed": "2026-05-26",
            "evidence_checked_at": "2026-05-26",
        },
    ],
}
